### ISSUE TITLE
Missing support for HSB / HSV

### ISSUE THREAD

**Issue by ChristophLabacher** [opencolor-tools/opencolor-js#21]
HSB might not be supported in CSS, but it is still extremely important as Sketch and Photoshop show values in HSB, not HSL.

**Comment by halfbyte** [comment]
Interesting. Again, at this point, this is more of a renderer kind of issue (as long as we don't actively parse color values in the parser. The question is: what should we do about this. I think this needs additional discussion. @theflow @rockitbaby

**Comment by halfbyte** [comment]
@ChristophLabacher We've been talking about "really" parsing identifiable color values and being able to convert them to rgb on the fly, so I'm closing this and turning it into a Trello ticket for future reference, okay?
