### ISSUE TITLE
parser fails if entry name contains true

### ISSUE THREAD

**Issue by rockitbaby** [opencolor-tools/opencolor-js#35]
```
darkish purple: #751973
true green: #089404
coral pink: #ff6163
```

Unexpected TRUE

**Comment by halfbyte** [comment]
Again, a case of too specific parsing. Will be fixed with the naive parser rewrite I'm pretty certain to attack next week as well.

**Comment by halfbyte** [comment]
Fixed in current versions, I just checked.
